### PR TITLE
Determine ECDSA curve from certificate, not hash algorithm

### LINKED ISSUE #56: DTLS 1.2: ECDSA signature verification incorrectly assumes curve from hash algorithm
Both `aws_lc_rs` and `rust_crypto` backends hardcode a 1:1 mapping between hash algorithm and EC curve in `SignatureVerifier::verify_signature`, causing handshake failures against servers that use a P-384 key with SHA256 signatures — a valid combination in DTLS 1.2. *This strict mapping is correct in DTLS 1.3.*

**`aws_lc_rs`**
https://github.com/algesten/dimpl/blob/3a6e9bd64aa4205d850a0817546dd1bd1a32d931/src/crypto/aws_lc_rs/sign.rs#L191-L200

**`rust_crypto`**
https://github.com/algesten/dimpl/blob/3a6e9bd64aa4205d850a0817546dd1bd1a32d931/src/crypto/rust_crypto/sign.rs#L204-L247

The verification algorithm should be selected based on the actual curve of the certificate's public key, not the hash algorithm alone. All cross-curve/hash combinations are affected (P-384 + SHA256, P-256 + SHA384).

### PR DESCRIPTION
**Pull request by algesten**
In DTLS 1.2, the hash algorithm and EC curve are independent choices.
A server may use a P-384 key with SHA-256 signatures (or vice versa).
Both aws-lc-rs and rust-crypto backends incorrectly assumed a 1:1
mapping (SHA-256 to P-256, SHA-384 to P-384), causing verification
failures for valid cross-curve/hash combinations.

Extract the actual curve OID from the certificate SPKI parameters
and select the verification algorithm from an allow-list of all four
supported (curve, hash) combinations.

Close #56

### CODE REVIEW

File: src/crypto/aws_lc_rs/sign.rs [hunk 1]
```diff
@@ -188,15 +190,32 @@ impl SignatureVerifier for AwsLcSignatureVerifier {
...
-            }
+        let curve_oid: ObjectIdentifier = spki
+            .algorithm
+            .parameters
+            .as_ref()
+            .ok_or("Missing EC curve parameter in certificate")?
+            .decode_as()
+            .map_err(|_| "Invalid EC curve parameter in certificate".to_string())?;
+
+        const OID_P256: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.10045.3.1.7");
```
Comment (xnorpx) [inline src/crypto/aws_lc_rs/sign.rs]: should you remove these to const mod in src/crypto to avoid dupe between the crypto impl?

File: src/crypto/rust_crypto/sign.rs [hunk 2]
```diff
@@ -201,47 +201,57 @@ impl SignatureVerifier for RustCryptoSignatureVerifier {
...
-
-                // Hash the data before verification (PrehashVerifier expects a hash digest)
-                let mut hasher = Sha256::new();
-                hasher.update(data);
-                let hash = hasher.finalize();
-
                 verifying_key
-                    .verify_prehash(&hash, &signature)
+                    .verify_prehash(&hash, &sig)
                     .map_err(|_| format!("ECDSA signature verification failed for {:?}", hash_alg))
```
Comment (xnorpx) [inline src/crypto/rust_crypto/sign.rs]: nit: add group as well?
